#############################################################################
# Makefile for building: FluidSim
# Generated by qmake (2.01a) (Qt 4.8.3) on: Fri May 10 05:30:57 2013
# Project:  FluidSim.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile FluidSim.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = gcc
DEFINES       = -DQT_WEBKIT -DGL_DO_NOT_WARN_IF_MULTI_GL_VERSION_HEADERS_INCLUDED -DNGL_DEBUG -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -msse -msse2 -msse3 -march=native -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXml -I/usr/include/qt4 -Iinclude -I+= -Iui -I../NGL/include -I/usr/X11R6/include -I. -Iui
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/X11R6/lib -L/usr/local/lib -L/$(HOME)/NGL/lib -l NGL -lQtXml -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/MainWindow.cpp \
		src/GLWindow.cpp \
		src/Particle.cpp \
		src/FluidSystem.cpp \
		src/Grid.cpp \
		src/FluidBBox.cpp \
		src/Parser.cpp \
		src/Obstacle.cpp \
		src/Sphere.cpp \
		src/Cube.cpp \
		src/MarchingCubes.cpp \
		src/GridCell.cpp \
		src/MCGrid.cpp moc_MainWindow.cpp \
		moc_GLWindow.cpp
OBJECTS       = main.o \
		MainWindow.o \
		GLWindow.o \
		Particle.o \
		FluidSystem.o \
		Grid.o \
		FluidBBox.o \
		Parser.o \
		Obstacle.o \
		Sphere.o \
		Cube.o \
		MarchingCubes.o \
		GridCell.o \
		MCGrid.o \
		moc_MainWindow.o \
		moc_GLWindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		FluidSim.pro
QMAKE_TARGET  = FluidSim
DESTDIR       = 
TARGET        = FluidSim

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui/ui_MainWindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: FluidSim.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile FluidSim.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile FluidSim.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/FluidSim1.0.0 || $(MKDIR) .tmp/FluidSim1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/FluidSim1.0.0/ && $(COPY_FILE) --parents include/MainWindow.h include/GLWindow.h include/Particle.h include/FluidSystem.h include/Grid.h include/FluidBBox.h include/Parser.h include/Obstacle.h include/Common.h include/Sphere.h include/Cube.h include/GridCell.h include/MarchingCubes.h include/MCGrid.h .tmp/FluidSim1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/MainWindow.cpp src/GLWindow.cpp src/Particle.cpp src/FluidSystem.cpp src/Grid.cpp src/FluidBBox.cpp src/Parser.cpp src/Obstacle.cpp src/Sphere.cpp src/Cube.cpp src/MarchingCubes.cpp src/GridCell.cpp src/MCGrid.cpp .tmp/FluidSim1.0.0/ && $(COPY_FILE) --parents ui/MainWindow.ui .tmp/FluidSim1.0.0/ && (cd `dirname .tmp/FluidSim1.0.0` && $(TAR) FluidSim1.0.0.tar FluidSim1.0.0 && $(COMPRESS) FluidSim1.0.0.tar) && $(MOVE) `dirname .tmp/FluidSim1.0.0`/FluidSim1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/FluidSim1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_MainWindow.cpp moc_GLWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp moc_GLWindow.cpp
moc_MainWindow.cpp: include/GLWindow.h \
		include/FluidBBox.h \
		include/Common.h \
		include/Particle.h \
		include/FluidSystem.h \
		include/Grid.h \
		include/GridCell.h \
		include/MarchingCubes.h \
		include/MCGrid.h \
		include/Obstacle.h \
		include/Parser.h \
		include/MainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/MainWindow.h -o moc_MainWindow.cpp

moc_GLWindow.cpp: include/FluidBBox.h \
		include/Common.h \
		include/Particle.h \
		include/FluidSystem.h \
		include/Grid.h \
		include/GridCell.h \
		include/MarchingCubes.h \
		include/MCGrid.h \
		include/Obstacle.h \
		include/Parser.h \
		include/GLWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/GLWindow.h -o moc_GLWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui/ui_MainWindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui/ui_MainWindow.h
ui/ui_MainWindow.h: ui/MainWindow.ui
	/usr/bin/uic-qt4 ui/MainWindow.ui -o ui/ui_MainWindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp include/MainWindow.h \
		include/GLWindow.h \
		include/FluidBBox.h \
		include/Common.h \
		include/Particle.h \
		include/FluidSystem.h \
		include/Grid.h \
		include/GridCell.h \
		include/MarchingCubes.h \
		include/MCGrid.h \
		include/Obstacle.h \
		include/Parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

MainWindow.o: src/MainWindow.cpp include/GLWindow.h \
		include/FluidBBox.h \
		include/Common.h \
		include/Particle.h \
		include/FluidSystem.h \
		include/Grid.h \
		include/GridCell.h \
		include/MarchingCubes.h \
		include/MCGrid.h \
		include/Obstacle.h \
		include/Parser.h \
		include/MainWindow.h \
		ui/ui_MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o src/MainWindow.cpp

GLWindow.o: src/GLWindow.cpp include/GLWindow.h \
		include/FluidBBox.h \
		include/Common.h \
		include/Particle.h \
		include/FluidSystem.h \
		include/Grid.h \
		include/GridCell.h \
		include/MarchingCubes.h \
		include/MCGrid.h \
		include/Obstacle.h \
		include/Parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLWindow.o src/GLWindow.cpp

Particle.o: src/Particle.cpp include/GLWindow.h \
		include/FluidBBox.h \
		include/Common.h \
		include/Particle.h \
		include/FluidSystem.h \
		include/Grid.h \
		include/GridCell.h \
		include/MarchingCubes.h \
		include/MCGrid.h \
		include/Obstacle.h \
		include/Parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Particle.o src/Particle.cpp

FluidSystem.o: src/FluidSystem.cpp include/FluidSystem.h \
		include/FluidBBox.h \
		include/Common.h \
		include/Particle.h \
		include/Grid.h \
		include/GridCell.h \
		include/MarchingCubes.h \
		include/MCGrid.h \
		include/Obstacle.h \
		include/Parser.h \
		include/Sphere.h \
		include/Cube.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FluidSystem.o src/FluidSystem.cpp

Grid.o: src/Grid.cpp include/Grid.h \
		include/GridCell.h \
		include/Particle.h \
		include/Common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Grid.o src/Grid.cpp

FluidBBox.o: src/FluidBBox.cpp include/FluidBBox.h \
		include/Common.h \
		include/Particle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FluidBBox.o src/FluidBBox.cpp

Parser.o: src/Parser.cpp include/Parser.h \
		include/Common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Parser.o src/Parser.cpp

Obstacle.o: src/Obstacle.cpp include/Obstacle.h \
		include/Parser.h \
		include/Common.h \
		include/Particle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Obstacle.o src/Obstacle.cpp

Sphere.o: src/Sphere.cpp include/FluidSystem.h \
		include/FluidBBox.h \
		include/Common.h \
		include/Particle.h \
		include/Grid.h \
		include/GridCell.h \
		include/MarchingCubes.h \
		include/MCGrid.h \
		include/Obstacle.h \
		include/Parser.h \
		include/Sphere.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Sphere.o src/Sphere.cpp

Cube.o: src/Cube.cpp include/Cube.h \
		include/Obstacle.h \
		include/Parser.h \
		include/Common.h \
		include/Particle.h \
		include/FluidSystem.h \
		include/FluidBBox.h \
		include/Grid.h \
		include/GridCell.h \
		include/MarchingCubes.h \
		include/MCGrid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cube.o src/Cube.cpp

MarchingCubes.o: src/MarchingCubes.cpp include/MarchingCubes.h \
		include/MCGrid.h \
		include/GridCell.h \
		include/Particle.h \
		include/Common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MarchingCubes.o src/MarchingCubes.cpp

GridCell.o: src/GridCell.cpp include/GridCell.h \
		include/Particle.h \
		include/Common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GridCell.o src/GridCell.cpp

MCGrid.o: src/MCGrid.cpp include/MCGrid.h \
		include/GridCell.h \
		include/Particle.h \
		include/Common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MCGrid.o src/MCGrid.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_GLWindow.o: moc_GLWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GLWindow.o moc_GLWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

